import Head from 'next/head';
import Image from 'next/image';
import {
  AppProvider,
  Box,
  HStack,
  Text,
  VStack,
} from '@gluestack/design-system';

export default function Home() {
  return (
    <AppProvider>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by node glue add web' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box flex={1} bg='$black'>
        <Box
          position='absolute'
          base-h={500}
          base-w={500}
          lg-h={700}
          lg-w={700}
        >
          <Image src='/gradient.svg' alt='Gradient' fill priority />
        </Box>
        <Box
          flex={1}
          base-my='$16'
          base-mx='$5'
          lg-my='$24'
          lg-mx='$32'
          alignItems='center'
        >
          <HStack
            bg='#64748B33'
            py='$2'
            px='$6'
            alignSelf='flex-start'
            rounded='$full'
          >
            <Text color='$white' fontWeight='400'>
              Get started by editing
            </Text>
            <Text color='$white' fontWeight='500' ml='$2'>
              pages/index.tsx
            </Text>
          </HStack>
          <Box
            flex={1}
            justifyContent='center'
            alignItems='center'
            base-w={300}
            base-h={20}
            lg-w={400}
            lg-h={160}
          >
            <Image src='/logo.svg' fill alt='logo' priority />
          </Box>
          <Box base-flexDirection='column' md-flexDirection='row'>
            <VStack
              borderWidth='1px'
              borderColor='$borderDark700'
              flex={1}
              m='$2'
              p='$4'
              rounded='$md'
            >
              <HStack alignItems='center'>
                <Image
                  src='/document-data.svg'
                  alt='document'
                  width={22}
                  height={22}
                  priority
                />
                <Text fontSize='22px' color='$white' fontWeight='500' ml='$2'>
                  Docs
                </Text>
              </HStack>
              <Text color='$textDark400' mt='$2'>
                Find in-depth information about gluestack features and API.
              </Text>
            </VStack>
            <VStack
              borderWidth='1px'
              borderColor='$borderDark700'
              flex={1}
              m='$2'
              p='$4'
              rounded='$md'
            >
              <HStack alignItems='center'>
                <Image
                  src='/lightbulb-person.svg'
                  alt='lightbulb'
                  width={22}
                  height={22}
                  priority
                />
                <Text fontSize='22px' color='$white' fontWeight='500' ml='$2'>
                  Learn
                </Text>
              </HStack>
              <Text color='$textDark400' mt='$2'>
                Learn about gluestack in an interactive course with quizzes!
              </Text>
            </VStack>
            <VStack
              borderWidth='1px'
              borderColor='$borderDark700'
              flex={1}
              m='$2'
              p='$4'
              rounded='$md'
            >
              <HStack alignItems='center'>
                <Image
                  src='/rocket.svg'
                  alt='rocket'
                  width={22}
                  height={22}
                  priority
                />
                <Text fontSize='22px' color='$white' fontWeight='500' ml='$2'>
                  Deploy
                </Text>
              </HStack>
              <Text color='$textDark400' mt='$2'>
                Instantly drop your gluestack site to a shareable URL with
                vercel.
              </Text>
            </VStack>
          </Box>
        </Box>
      </Box>
    </AppProvider>
  );
}
