import Head from 'next/head';
import Image from 'next/image';
import {
  AppProvider,
  Box,
  HStack,
  Text,
  VStack,
} from '@gluestack/design-system';

const Meta = () => {
  return (
    <Head>
      <title>Create Gluestack App</title>
      <meta name='description' content='Generated by node glue add web' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  );
};

const FeatureCard = ({ iconSvg, name, desc }: any) => {
  return (
    <VStack
      borderWidth='1px'
      borderColor='$borderDark700'
      flex={1}
      m='$2'
      p='$4'
      rounded='$md'
    >
      <HStack alignItems='center'>
        <Image
          src={`/${iconSvg}`}
          alt='document'
          width={22}
          height={22}
          priority
        />
        <Text fontSize='22px' color='$white' fontWeight='500' ml='$2'>
          {name}
        </Text>
      </HStack>
      <Text color='$textDark400' mt='$2'>
        {desc}
      </Text>
    </VStack>
  );
};

const Example = () => {
  return (
    <Box flex={1} bg='$black'>
      <Box position='absolute' base-h={500} base-w={500} lg-h={700} lg-w={700}>
        <Image src='/gradient.svg' alt='Gradient' fill priority />
      </Box>
      <Box
        flex={1}
        base-my='$16'
        base-mx='$5'
        lg-my='$24'
        lg-mx='$32'
        alignItems='center'
      >
        <Box
          bg='#64748B33'
          py='$2'
          px='$6'
          md-alignSelf='flex-start'
          rounded='$full'
          base-flexDirection='column'
          sm-flexDirection='row'
          alignItems='center'
        >
          <Text color='$white' fontWeight='$normal'>
            Get started by editing
          </Text>
          <Text color='$white' fontWeight='$medium' ml='$2'>
            pages/index.tsx
          </Text>
        </Box>
        <Box
          flex={1}
          justifyContent='center'
          alignItems='center'
          base-w={300}
          base-h={20}
          lg-w={400}
          lg-h={160}
        >
          <Image src='/logo.svg' fill alt='logo' priority />
        </Box>
        <Box base-flexDirection='column' md-flexDirection='row'>
          <FeatureCard
            iconSvg='document-data.svg'
            name='Docs'
            desc='Find in-depth information about gluestack features and API.'
          />
          <FeatureCard
            iconSvg='lightbulb-person.svg'
            name='Learn'
            desc='Learn about gluestack in an interactive course with quizzes!'
          />
          <FeatureCard
            iconSvg='rocket.svg'
            name='Deploy'
            desc='Instantly drop your gluestack site to a shareable URL with vercel.'
          />
        </Box>
      </Box>
    </Box>
  );
};

export default function Home() {
  return (
    <AppProvider>
      <Meta />
      <Example />
    </AppProvider>
  );
}
